service: s3-file-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-west-2
  apiName: ${self:service}
  memorySize: 128 
  timeout: 10 
  environment:
    FILE_UPLOAD_BUCKET_NAME: ${self:custom.fileBucketName}

plugins:
  - serverless-iam-roles-per-function

custom:
  fileBucketName: s3-file-bucket-${self:provider.stage}
functions:
  s3FileUploader:
    handler: src/upload.handler
    name: s3-file-uploader
    description: A lambda that uploads a file to an s3 bucket based on an API Gateway trigger.
    events:
      - http:
          path: file
          method: POST 
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 's3:Put*'
        Resource: arn:aws:s3:::${self:custom.fileBucketName}/*
resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileBucketName}
        AccessControl: Private